CREATE TABLE boat (
  id INT AUTO_INCREMENT NOT NULL,
  name VARCHAR(255) NOT NULL,
  coord_x INT NOT NULL,
  coord_y INT NOT NULL,
  PRIMARY KEY(id)
);

CREATE TABLE tile (
  id INT AUTO_INCREMENT NOT NULL,
  type VARCHAR(255) NOT NULL,
  coord_x INT NOT NULL,
  coord_y INT NOT NULL,
  PRIMARY KEY(id)
);

-- CREATE TABLE album (
--   id INT AUTO_INCREMENT NOT NULL,
--   title VARCHAR(50) NOT NULL, 
--   genre VARCHAR(50) NOT NULL, 
--   image BLOB NOT NULL,
--   artiste VARCHAR(50) NOT NULL, 
--   track VARCHAR(255) NOT NULL, 
--   PRIMARY KEY(id)
-- )